# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Server
    init: |
      npm install -g pnpm
      pnpm install

    command: |
      npm install -g pnpm
      pnpm start
      curl -sL https://firebase.tools | bash
    openMode: split-left

  - openMode: split-right

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8000
    onOpen: ignore
